### ISSUE TITLE
.git/ should be unconditionally ignored

### ISSUE THREAD

**Issue by zkat** [npm/ignore-walk#2]
...just like git itself ignores that directory, due to inception issues. This is a regression from fstream.

**Comment by zhaochy1990** [comment]
agreed

**Comment by zhaochy1990** [comment]
@isaacs can u update this module so that we can add ignore rules by default
e.g. for node users if no ignore files specified, this module will pack `node_modules`, `.git`, etc
this can be ignored by setting a default ignore list

**Comment by gabrielcsapo** [comment]
@isaacs are you accepting PRs for this repo still?

**Comment by thekoushik** [comment]
I'm doing this way..

```javascript
var walk=require('ignore-walk');
var minimatch=require('minimatch');

exports.getGitIgnoredFiles=(dir,customIgnores)=>{// customIgnores is OPTIONAL
    var walker=new walk.WalkerSync({
        path:dir || process.cwd(),
        ignoreFiles:[".gitignore",'.customignore']
    });
    walker.ignoreRules['.customignore']=[
        new minimatch.Minimatch('.git/*',{matchBase: true,dot: true,flipNegate: true,nocase: true})
    ];
    if(customIgnores){
        (Array.isArray(customIgnores)?customIgnores:[customIgnores]).forEach(ex=>{
            walker.ignoreRules['.customignore'].push(new minimatch.Minimatch(ex,{
                matchBase: true,nocase: true
            }))
        })
    }
    return walker.start().result;
}
```

**Comment by Thorarin** [comment]
I also wanted to add some predefined ignore rules, so I used a similar way as @thekoushik.
Only instead of creating the Minimatch objects, I'm abusing the `onReadIgnoreFile` method that happens to be available:

So for example in the use case of the original reporter:
```walker.onReadIgnoreFile('.customignore', '.git', () => {})```

Both of these solutions are pretty ugly though. I have to make up an extra ignore file name that I don't really want. Users inspecting the source code could decide to create a file with that name and overwrite my default rules.

@isaacs A way to add default rules, that is part of the official public API would be very nice.

Pretty nasty hack, but adding this in the constructor of `Walker` seems to work:

```
if (opts.ignoreRules) {
    this.ignoreFiles = this.ignoreFiles.concat('')
    this.onReadIgnoreFile('', opts.ignoreRules, function() {})
}
```

- I don't think there should ever  be a file entry with a zero length name.
- Don't modify the existing array that is taken directly from the `opts`
- I want my default rules to be evaluated last so they cannot be overridden.

**Comment by wraithgar** [comment]
Closing for the same reason as https://github.com/npm/ignore-walk/pull/6, this is a packlist concern.
